### PR TITLE
feature: support node 16

### PR DESCRIPTION
**Pull request by miniscruff**
Follow this post https://github.com/bcoin-org/bcrypto/issues/7 to swap to the supported APIs, seems to work locally but we have no CI here for testing or anything.

### CODE REVIEW

**Comment by vrancurel** [comment]
Did you try running https://github.com/scality/node-fcntl/blob/master/examples/fadv_dontneed.js at least locally ?

**Comment by miniscruff** [comment]
> Did you try running https://github.com/scality/node-fcntl/blob/master/examples/fadv_dontneed.js at least locally ?

```
▶ node fadv_dontneed.js
posixFadvise ret: 0
```
Is this right?

**Review by nicolas2bert — APPROVED** [review]
Do we want to add the engines property in package.json to specify the required/supported nodeJS versions?

**Review by naren-rajendran — APPROVED** [review]

**Comment by vrancurel** [comment]
> > Did you try running https://github.com/scality/node-fcntl/blob/master/examples/fadv_dontneed.js at least locally ?
> 
> ```
> ▶ node fadv_dontneed.js
> posixFadvise ret: 0
> ```
> 
> Is this right?

it looks right

**Pull request merged**
